//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class GameCore_SceneManagerWrap
{
	public static void Register(LuaState L)
	{
		L.BeginStaticLibs("SceneManager");
		L.EndStaticLibs();
	}
}

