//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: BattleInfomationData.proto
namespace BattleInfomationData
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BattleInfomationDatatable")]
  public partial class BattleInfomationDatatable : global::ProtoBuf.IExtensible
  {
    public BattleInfomationDatatable() {}
    
    private string _tname = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string tname
    {
      get { return _tname; }
      set { _tname = value; }
    }
    private readonly global::System.Collections.Generic.List<BattleInfomationData> _tlist = new global::System.Collections.Generic.List<BattleInfomationData>();
    [global::ProtoBuf.ProtoMember(2, Name=@"tlist", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<BattleInfomationData> tlist
    {
      get { return _tlist; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BattleInfomationData")]
  public partial class BattleInfomationData : global::ProtoBuf.IExtensible
  {
    public BattleInfomationData() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _ActiveSkill = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"ActiveSkill", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> ActiveSkill
    {
      get { return _ActiveSkill; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _TimeToCD = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(3, Name=@"TimeToCD", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> TimeToCD
    {
      get { return _TimeToCD; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _AutoSkill2 = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(4, Name=@"AutoSkill2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> AutoSkill2
    {
      get { return _AutoSkill2; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _AutoSkill3 = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(5, Name=@"AutoSkill3", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> AutoSkill3
    {
      get { return _AutoSkill3; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _AutoSkill4 = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(6, Name=@"AutoSkill4", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> AutoSkill4
    {
      get { return _AutoSkill4; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _AutoSkill5 = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(7, Name=@"AutoSkill5", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> AutoSkill5
    {
      get { return _AutoSkill5; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _AutoSkill6 = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(8, Name=@"AutoSkill6", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> AutoSkill6
    {
      get { return _AutoSkill6; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _AutoSkill7 = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(9, Name=@"AutoSkill7", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> AutoSkill7
    {
      get { return _AutoSkill7; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _AutoSkill8 = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(10, Name=@"AutoSkill8", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> AutoSkill8
    {
      get { return _AutoSkill8; }
    }
  
    private int _CaptainSkill = default(int);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"CaptainSkill", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int CaptainSkill
    {
      get { return _CaptainSkill; }
      set { _CaptainSkill = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _DragAiID = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(12, Name=@"DragAiID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> DragAiID
    {
      get { return _DragAiID; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _ActiveSkill_AI = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(13, Name=@"ActiveSkill_AI", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> ActiveSkill_AI
    {
      get { return _ActiveSkill_AI; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _AutoSkill1_AI = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(14, Name=@"AutoSkill1_AI", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> AutoSkill1_AI
    {
      get { return _AutoSkill1_AI; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _AutoSkill2_AI = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(15, Name=@"AutoSkill2_AI", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> AutoSkill2_AI
    {
      get { return _AutoSkill2_AI; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _AutoSkill3_AI = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(16, Name=@"AutoSkill3_AI", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> AutoSkill3_AI
    {
      get { return _AutoSkill3_AI; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _AutoSkill4_AI = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(17, Name=@"AutoSkill4_AI", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> AutoSkill4_AI
    {
      get { return _AutoSkill4_AI; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _AutoSkill5_AI = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(18, Name=@"AutoSkill5_AI", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> AutoSkill5_AI
    {
      get { return _AutoSkill5_AI; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _AutoSkill6_AI = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(19, Name=@"AutoSkill6_AI", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> AutoSkill6_AI
    {
      get { return _AutoSkill6_AI; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _AutoSkill7_AI = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(20, Name=@"AutoSkill7_AI", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> AutoSkill7_AI
    {
      get { return _AutoSkill7_AI; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _AutoSkill8_AI = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(21, Name=@"AutoSkill8_AI", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> AutoSkill8_AI
    {
      get { return _AutoSkill8_AI; }
    }
  
    private int _SimpleAttackSkill1 = default(int);
    [global::ProtoBuf.ProtoMember(22, IsRequired = false, Name=@"SimpleAttackSkill1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int SimpleAttackSkill1
    {
      get { return _SimpleAttackSkill1; }
      set { _SimpleAttackSkill1 = value; }
    }
    private int _SimpleAttackSkill2 = default(int);
    [global::ProtoBuf.ProtoMember(23, IsRequired = false, Name=@"SimpleAttackSkill2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int SimpleAttackSkill2
    {
      get { return _SimpleAttackSkill2; }
      set { _SimpleAttackSkill2 = value; }
    }
    private int _SimpleAttackSkill3 = default(int);
    [global::ProtoBuf.ProtoMember(24, IsRequired = false, Name=@"SimpleAttackSkill3", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int SimpleAttackSkill3
    {
      get { return _SimpleAttackSkill3; }
      set { _SimpleAttackSkill3 = value; }
    }
    private int _SimpleAttackSkill4 = default(int);
    [global::ProtoBuf.ProtoMember(25, IsRequired = false, Name=@"SimpleAttackSkill4", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int SimpleAttackSkill4
    {
      get { return _SimpleAttackSkill4; }
      set { _SimpleAttackSkill4 = value; }
    }
    private int _SimpleAttackSkill5 = default(int);
    [global::ProtoBuf.ProtoMember(26, IsRequired = false, Name=@"SimpleAttackSkill5", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int SimpleAttackSkill5
    {
      get { return _SimpleAttackSkill5; }
      set { _SimpleAttackSkill5 = value; }
    }
    private int _SimpleAttackSkill6 = default(int);
    [global::ProtoBuf.ProtoMember(27, IsRequired = false, Name=@"SimpleAttackSkill6", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int SimpleAttackSkill6
    {
      get { return _SimpleAttackSkill6; }
      set { _SimpleAttackSkill6 = value; }
    }
    private int _ManualAttack_AI = default(int);
    [global::ProtoBuf.ProtoMember(28, IsRequired = false, Name=@"ManualAttack_AI", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ManualAttack_AI
    {
      get { return _ManualAttack_AI; }
      set { _ManualAttack_AI = value; }
    }
    private int _SimpleAttackSkill1_AI = default(int);
    [global::ProtoBuf.ProtoMember(29, IsRequired = false, Name=@"SimpleAttackSkill1_AI", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int SimpleAttackSkill1_AI
    {
      get { return _SimpleAttackSkill1_AI; }
      set { _SimpleAttackSkill1_AI = value; }
    }
    private int _SimpleAttackSkill2_AI = default(int);
    [global::ProtoBuf.ProtoMember(30, IsRequired = false, Name=@"SimpleAttackSkill2_AI", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int SimpleAttackSkill2_AI
    {
      get { return _SimpleAttackSkill2_AI; }
      set { _SimpleAttackSkill2_AI = value; }
    }
    private int _SimpleAttackSkill3_AI = default(int);
    [global::ProtoBuf.ProtoMember(31, IsRequired = false, Name=@"SimpleAttackSkill3_AI", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int SimpleAttackSkill3_AI
    {
      get { return _SimpleAttackSkill3_AI; }
      set { _SimpleAttackSkill3_AI = value; }
    }
    private int _SimpleAttackSkill4_AI = default(int);
    [global::ProtoBuf.ProtoMember(32, IsRequired = false, Name=@"SimpleAttackSkill4_AI", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int SimpleAttackSkill4_AI
    {
      get { return _SimpleAttackSkill4_AI; }
      set { _SimpleAttackSkill4_AI = value; }
    }
    private int _SimpleAttackSkill5_AI = default(int);
    [global::ProtoBuf.ProtoMember(33, IsRequired = false, Name=@"SimpleAttackSkill5_AI", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int SimpleAttackSkill5_AI
    {
      get { return _SimpleAttackSkill5_AI; }
      set { _SimpleAttackSkill5_AI = value; }
    }
    private int _SimpleAttackSkill6_AI = default(int);
    [global::ProtoBuf.ProtoMember(34, IsRequired = false, Name=@"SimpleAttackSkill6_AI", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int SimpleAttackSkill6_AI
    {
      get { return _SimpleAttackSkill6_AI; }
      set { _SimpleAttackSkill6_AI = value; }
    }
    private string _modelPath = "";
    [global::ProtoBuf.ProtoMember(35, IsRequired = false, Name=@"modelPath", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string modelPath
    {
      get { return _modelPath; }
      set { _modelPath = value; }
    }
    private string _simpleModelPath = "";
    [global::ProtoBuf.ProtoMember(36, IsRequired = false, Name=@"simpleModelPath", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string simpleModelPath
    {
      get { return _simpleModelPath; }
      set { _simpleModelPath = value; }
    }
    private string _cityModelPath = "";
    [global::ProtoBuf.ProtoMember(37, IsRequired = false, Name=@"cityModelPath", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string cityModelPath
    {
      get { return _cityModelPath; }
      set { _cityModelPath = value; }
    }
    private string _picName = "";
    [global::ProtoBuf.ProtoMember(38, IsRequired = false, Name=@"picName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string picName
    {
      get { return _picName; }
      set { _picName = value; }
    }
    private string _BigPicName = "";
    [global::ProtoBuf.ProtoMember(39, IsRequired = false, Name=@"BigPicName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string BigPicName
    {
      get { return _BigPicName; }
      set { _BigPicName = value; }
    }
    private float _alertDistance = default(float);
    [global::ProtoBuf.ProtoMember(40, IsRequired = false, Name=@"alertDistance", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float alertDistance
    {
      get { return _alertDistance; }
      set { _alertDistance = value; }
    }
    private float _attackDistance = default(float);
    [global::ProtoBuf.ProtoMember(41, IsRequired = false, Name=@"attackDistance", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float attackDistance
    {
      get { return _attackDistance; }
      set { _attackDistance = value; }
    }
    private float _DestroyBodyTime = default(float);
    [global::ProtoBuf.ProtoMember(42, IsRequired = false, Name=@"DestroyBodyTime", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float DestroyBodyTime
    {
      get { return _DestroyBodyTime; }
      set { _DestroyBodyTime = value; }
    }
    private int _DeathType_1_Behavior = default(int);
    [global::ProtoBuf.ProtoMember(43, IsRequired = false, Name=@"DeathType_1_Behavior", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int DeathType_1_Behavior
    {
      get { return _DeathType_1_Behavior; }
      set { _DeathType_1_Behavior = value; }
    }
    private int _DeathType_2_Behavior = default(int);
    [global::ProtoBuf.ProtoMember(44, IsRequired = false, Name=@"DeathType_2_Behavior", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int DeathType_2_Behavior
    {
      get { return _DeathType_2_Behavior; }
      set { _DeathType_2_Behavior = value; }
    }
    private int _DeathType_3_Behavior = default(int);
    [global::ProtoBuf.ProtoMember(45, IsRequired = false, Name=@"DeathType_3_Behavior", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int DeathType_3_Behavior
    {
      get { return _DeathType_3_Behavior; }
      set { _DeathType_3_Behavior = value; }
    }
    private int _Quality = default(int);
    [global::ProtoBuf.ProtoMember(46, IsRequired = false, Name=@"Quality", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Quality
    {
      get { return _Quality; }
      set { _Quality = value; }
    }
    private readonly global::System.Collections.Generic.List<float> _LeftPosition = new global::System.Collections.Generic.List<float>();
    [global::ProtoBuf.ProtoMember(47, Name=@"LeftPosition", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public global::System.Collections.Generic.List<float> LeftPosition
    {
      get { return _LeftPosition; }
    }
  
    private readonly global::System.Collections.Generic.List<float> _RightPosition = new global::System.Collections.Generic.List<float>();
    [global::ProtoBuf.ProtoMember(48, Name=@"RightPosition", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public global::System.Collections.Generic.List<float> RightPosition
    {
      get { return _RightPosition; }
    }
  
    private int _AnimatorFlagID = default(int);
    [global::ProtoBuf.ProtoMember(49, IsRequired = false, Name=@"AnimatorFlagID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int AnimatorFlagID
    {
      get { return _AnimatorFlagID; }
      set { _AnimatorFlagID = value; }
    }
    private int _PositionIndex = default(int);
    [global::ProtoBuf.ProtoMember(50, IsRequired = false, Name=@"PositionIndex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int PositionIndex
    {
      get { return _PositionIndex; }
      set { _PositionIndex = value; }
    }
    private int _modelColorID = default(int);
    [global::ProtoBuf.ProtoMember(51, IsRequired = false, Name=@"modelColorID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int modelColorID
    {
      get { return _modelColorID; }
      set { _modelColorID = value; }
    }
    private int _Flyability = default(int);
    [global::ProtoBuf.ProtoMember(52, IsRequired = false, Name=@"Flyability", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Flyability
    {
      get { return _Flyability; }
      set { _Flyability = value; }
    }
    private int _ClassType = default(int);
    [global::ProtoBuf.ProtoMember(53, IsRequired = false, Name=@"ClassType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ClassType
    {
      get { return _ClassType; }
      set { _ClassType = value; }
    }
    private int _MaxAttacker = default(int);
    [global::ProtoBuf.ProtoMember(54, IsRequired = false, Name=@"MaxAttacker", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int MaxAttacker
    {
      get { return _MaxAttacker; }
      set { _MaxAttacker = value; }
    }
    private float _PointModelScale = default(float);
    [global::ProtoBuf.ProtoMember(55, IsRequired = false, Name=@"PointModelScale", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float PointModelScale
    {
      get { return _PointModelScale; }
      set { _PointModelScale = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}