//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ConditionAttrTypeData.proto
namespace ConditionAttrTypeData
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ConditionAttrTypeDatatable")]
  public partial class ConditionAttrTypeDatatable : global::ProtoBuf.IExtensible
  {
    public ConditionAttrTypeDatatable() {}
    
    private string _tname = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string tname
    {
      get { return _tname; }
      set { _tname = value; }
    }
    private readonly global::System.Collections.Generic.List<ConditionAttrTypeData> _tlist = new global::System.Collections.Generic.List<ConditionAttrTypeData>();
    [global::ProtoBuf.ProtoMember(2, Name=@"tlist", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ConditionAttrTypeData> tlist
    {
      get { return _tlist; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ConditionAttrTypeData")]
  public partial class ConditionAttrTypeData : global::ProtoBuf.IExtensible
  {
    public ConditionAttrTypeData() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private int _Tag = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Tag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Tag
    {
      get { return _Tag; }
      set { _Tag = value; }
    }
    private string _Name = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Name
    {
      get { return _Name; }
      set { _Name = value; }
    }
    private int _AttrID = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"AttrID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int AttrID
    {
      get { return _AttrID; }
      set { _AttrID = value; }
    }
    private string _Des = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"Des", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Des
    {
      get { return _Des; }
      set { _Des = value; }
    }
    private int _AttrType = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"AttrType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int AttrType
    {
      get { return _AttrType; }
      set { _AttrType = value; }
    }
    private int _ParamSource = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"ParamSource", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ParamSource
    {
      get { return _ParamSource; }
      set { _ParamSource = value; }
    }
    private int _ReadExcelFuncParam = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"ReadExcelFuncParam", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ReadExcelFuncParam
    {
      get { return _ReadExcelFuncParam; }
      set { _ReadExcelFuncParam = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}