
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public enum DataTypeDefine
{
	DT_AiIDData                         = 1,
	DT_BuffDataSwitchForm               = 2,
	DT_BuffIdData                       = 3,
	DT_PassiveEffectData                = 4,
	DT_VirtualCreatureData              = 5,
	DT_CreatureData                     = 6,
	DT_TriggerData                      = 7,
	DT_SelectObjectData                 = 8,
	DT_CampReferenceData                = 9,
	DT_RuneData                         = 10,
	DT_HaloData                         = 11,
	DT_SectionStageInfoData             = 12,
	DT_DiffcultyStageInfoData           = 13,
	DT_StageResumeData                  = 14,
	DT_StageData                        = 15,
	DT_SkillData                        = 16,
	DT_PurseData                        = 17,
	DT_ControllStateData                = 18,
	DT_DamageValueInfoData              = 19,
	DT_ConditionsData                   = 20,
	DT_MotionData                       = 21,
	DT_GatherPassiveEffectData          = 22,
	DT_ModifyAttributeData              = 23,
	DT_EffectModifySkillCDData          = 24,
	DT_EffectHitEventData               = 25,
	DT_EffectData                       = 26,
	DT_BattleAttributeData              = 27,
	DT_DoorData                         = 28,
	DT_StarGrouthData                   = 29,
	DT_MonsterData                      = 30,
	DT_QualityGrouthData                = 31,
	DT_TowerData                        = 32,
	DT_CharacterData                    = 33,
	DT_BattleInfomationData             = 34,
	DT_AttributeDefineData              = 35,
	DT_BattleConfigData                 = 36,
	DT_HeroFormationData                = 37,
	DT_SoldierFormationData             = 38,

}