//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: MonsterData.proto
namespace MonsterData
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MonsterDatatable")]
  public partial class MonsterDatatable : global::ProtoBuf.IExtensible
  {
    public MonsterDatatable() {}
    
    private string _tname = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string tname
    {
      get { return _tname; }
      set { _tname = value; }
    }
    private readonly global::System.Collections.Generic.List<MonsterData> _tlist = new global::System.Collections.Generic.List<MonsterData>();
    [global::ProtoBuf.ProtoMember(2, Name=@"tlist", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MonsterData> tlist
    {
      get { return _tlist; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MonsterData")]
  public partial class MonsterData : global::ProtoBuf.IExtensible
  {
    public MonsterData() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private string _characterName = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"characterName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string characterName
    {
      get { return _characterName; }
      set { _characterName = value; }
    }
    private int _actorType = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"actorType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int actorType
    {
      get { return _actorType; }
      set { _actorType = value; }
    }
    private int _country = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"country", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int country
    {
      get { return _country; }
      set { _country = value; }
    }
    private int _battleInfo = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"battleInfo", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int battleInfo
    {
      get { return _battleInfo; }
      set { _battleInfo = value; }
    }
    private int _battleAttr = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"battleAttr", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int battleAttr
    {
      get { return _battleAttr; }
      set { _battleAttr = value; }
    }
    private int _BornSound = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"BornSound", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int BornSound
    {
      get { return _BornSound; }
      set { _BornSound = value; }
    }
    private int _DeathSound = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"DeathSound", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int DeathSound
    {
      get { return _DeathSound; }
      set { _DeathSound = value; }
    }
    private int _EliteLevel = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"EliteLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int EliteLevel
    {
      get { return _EliteLevel; }
      set { _EliteLevel = value; }
    }
    private int _PositionIndex = default(int);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"PositionIndex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int PositionIndex
    {
      get { return _PositionIndex; }
      set { _PositionIndex = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _SkillLevel = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(11, Name=@"SkillLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> SkillLevel
    {
      get { return _SkillLevel; }
    }
  
    private float _Height = default(float);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"Height", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float Height
    {
      get { return _Height; }
      set { _Height = value; }
    }
    private float _scale = default(float);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"scale", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float scale
    {
      get { return _scale; }
      set { _scale = value; }
    }
    private float _BodyRadius = default(float);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"BodyRadius", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float BodyRadius
    {
      get { return _BodyRadius; }
      set { _BodyRadius = value; }
    }
    private bool _isShowHp = default(bool);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"isShowHp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isShowHp
    {
      get { return _isShowHp; }
      set { _isShowHp = value; }
    }
    private string _MonsterIntro = "";
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"MonsterIntro", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string MonsterIntro
    {
      get { return _MonsterIntro; }
      set { _MonsterIntro = value; }
    }
    private string _BossInfo = "";
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"BossInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string BossInfo
    {
      get { return _BossInfo; }
      set { _BossInfo = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _BossAbilityTrend = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(18, Name=@"BossAbilityTrend", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> BossAbilityTrend
    {
      get { return _BossAbilityTrend; }
    }
  
    private int _skillIndex = default(int);
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"skillIndex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int skillIndex
    {
      get { return _skillIndex; }
      set { _skillIndex = value; }
    }
    private int _stopAnimatorTick = default(int);
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"stopAnimatorTick", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int stopAnimatorTick
    {
      get { return _stopAnimatorTick; }
      set { _stopAnimatorTick = value; }
    }
    private int _Quality = default(int);
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"Quality", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Quality
    {
      get { return _Quality; }
      set { _Quality = value; }
    }
    private int _soldierType = default(int);
    [global::ProtoBuf.ProtoMember(22, IsRequired = false, Name=@"soldierType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int soldierType
    {
      get { return _soldierType; }
      set { _soldierType = value; }
    }
    private int _SoldierFormationID = default(int);
    [global::ProtoBuf.ProtoMember(23, IsRequired = false, Name=@"SoldierFormationID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int SoldierFormationID
    {
      get { return _SoldierFormationID; }
      set { _SoldierFormationID = value; }
    }
    private string _SoldierIcon = "";
    [global::ProtoBuf.ProtoMember(24, IsRequired = false, Name=@"SoldierIcon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string SoldierIcon
    {
      get { return _SoldierIcon; }
      set { _SoldierIcon = value; }
    }
    private int _ChargeShowID = default(int);
    [global::ProtoBuf.ProtoMember(25, IsRequired = false, Name=@"ChargeShowID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ChargeShowID
    {
      get { return _ChargeShowID; }
      set { _ChargeShowID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}