//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: SectionData.proto
namespace SectionData
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SectionDatatable")]
  public partial class SectionDatatable : global::ProtoBuf.IExtensible
  {
    public SectionDatatable() {}
    
    private string _tname = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string tname
    {
      get { return _tname; }
      set { _tname = value; }
    }
    private readonly global::System.Collections.Generic.List<SectionData> _tlist = new global::System.Collections.Generic.List<SectionData>();
    [global::ProtoBuf.ProtoMember(2, Name=@"tlist", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<SectionData> tlist
    {
      get { return _tlist; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SectionData")]
  public partial class SectionData : global::ProtoBuf.IExtensible
  {
    public SectionData() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private string _SectionName = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"SectionName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string SectionName
    {
      get { return _SectionName; }
      set { _SectionName = value; }
    }
    private int _SectionID = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"SectionID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int SectionID
    {
      get { return _SectionID; }
      set { _SectionID = value; }
    }
    private int _Map = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"Map", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Map
    {
      get { return _Map; }
      set { _Map = value; }
    }
    private int _StageID = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"StageID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int StageID
    {
      get { return _StageID; }
      set { _StageID = value; }
    }
    private string _modelName = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"modelName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string modelName
    {
      get { return _modelName; }
      set { _modelName = value; }
    }
    private int _minLevel = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"minLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int minLevel
    {
      get { return _minLevel; }
      set { _minLevel = value; }
    }
    private string _WayName = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"WayName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string WayName
    {
      get { return _WayName; }
      set { _WayName = value; }
    }
    private string _MountName = "";
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"MountName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string MountName
    {
      get { return _MountName; }
      set { _MountName = value; }
    }
    private int _terrainID = default(int);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"terrainID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int terrainID
    {
      get { return _terrainID; }
      set { _terrainID = value; }
    }
    private int _weatherID = default(int);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"weatherID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int weatherID
    {
      get { return _weatherID; }
      set { _weatherID = value; }
    }
    private string _sectionDescribe = "";
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"sectionDescribe", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string sectionDescribe
    {
      get { return _sectionDescribe; }
      set { _sectionDescribe = value; }
    }
    private string _secIcon = "";
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"secIcon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string secIcon
    {
      get { return _secIcon; }
      set { _secIcon = value; }
    }
    private int _sectionType = default(int);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"sectionType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int sectionType
    {
      get { return _sectionType; }
      set { _sectionType = value; }
    }
    private string _FirstStarIntro = "";
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"FirstStarIntro", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string FirstStarIntro
    {
      get { return _FirstStarIntro; }
      set { _FirstStarIntro = value; }
    }
    private string _SecondStarIntro = "";
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"SecondStarIntro", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string SecondStarIntro
    {
      get { return _SecondStarIntro; }
      set { _SecondStarIntro = value; }
    }
    private string _ThirdStarIntro = "";
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"ThirdStarIntro", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ThirdStarIntro
    {
      get { return _ThirdStarIntro; }
      set { _ThirdStarIntro = value; }
    }
    private int _periodLv = default(int);
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"periodLv", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int periodLv
    {
      get { return _periodLv; }
      set { _periodLv = value; }
    }
    private int _difficulty = default(int);
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"difficulty", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int difficulty
    {
      get { return _difficulty; }
      set { _difficulty = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _FirstDropAward = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(20, Name=@"FirstDropAward", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> FirstDropAward
    {
      get { return _FirstDropAward; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _DropAward = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(21, Name=@"DropAward", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> DropAward
    {
      get { return _DropAward; }
    }
  
    private int _CardExp = default(int);
    [global::ProtoBuf.ProtoMember(22, IsRequired = false, Name=@"CardExp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int CardExp
    {
      get { return _CardExp; }
      set { _CardExp = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _FailDropAward = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(23, Name=@"FailDropAward", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> FailDropAward
    {
      get { return _FailDropAward; }
    }
  
    private int _FailCardExp = default(int);
    [global::ProtoBuf.ProtoMember(24, IsRequired = false, Name=@"FailCardExp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int FailCardExp
    {
      get { return _FailCardExp; }
      set { _FailCardExp = value; }
    }
    private int _RegainConsumeID = default(int);
    [global::ProtoBuf.ProtoMember(25, IsRequired = false, Name=@"RegainConsumeID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int RegainConsumeID
    {
      get { return _RegainConsumeID; }
      set { _RegainConsumeID = value; }
    }
    private int _RegainConsumeBegin = default(int);
    [global::ProtoBuf.ProtoMember(26, IsRequired = false, Name=@"RegainConsumeBegin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int RegainConsumeBegin
    {
      get { return _RegainConsumeBegin; }
      set { _RegainConsumeBegin = value; }
    }
    private int _RegainConsumeEnd = default(int);
    [global::ProtoBuf.ProtoMember(27, IsRequired = false, Name=@"RegainConsumeEnd", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int RegainConsumeEnd
    {
      get { return _RegainConsumeEnd; }
      set { _RegainConsumeEnd = value; }
    }
    private int _QuickPassConsume = default(int);
    [global::ProtoBuf.ProtoMember(28, IsRequired = false, Name=@"QuickPassConsume", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int QuickPassConsume
    {
      get { return _QuickPassConsume; }
      set { _QuickPassConsume = value; }
    }
    private int _QuickPassExpDrop = default(int);
    [global::ProtoBuf.ProtoMember(29, IsRequired = false, Name=@"QuickPassExpDrop", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int QuickPassExpDrop
    {
      get { return _QuickPassExpDrop; }
      set { _QuickPassExpDrop = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _Bounty = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(30, Name=@"Bounty", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> Bounty
    {
      get { return _Bounty; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _OpenFunction = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(31, Name=@"OpenFunction", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> OpenFunction
    {
      get { return _OpenFunction; }
    }
  
    private int _BossID = default(int);
    [global::ProtoBuf.ProtoMember(32, IsRequired = false, Name=@"BossID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int BossID
    {
      get { return _BossID; }
      set { _BossID = value; }
    }
    private readonly global::System.Collections.Generic.List<float> _CameraPosition = new global::System.Collections.Generic.List<float>();
    [global::ProtoBuf.ProtoMember(33, Name=@"CameraPosition", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public global::System.Collections.Generic.List<float> CameraPosition
    {
      get { return _CameraPosition; }
    }
  
    private string _SectionType = "";
    [global::ProtoBuf.ProtoMember(34, IsRequired = false, Name=@"SectionType", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string SectionType
    {
      get { return _SectionType; }
      set { _SectionType = value; }
    }
    private string _SectionTypeName = "";
    [global::ProtoBuf.ProtoMember(35, IsRequired = false, Name=@"SectionTypeName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string SectionTypeName
    {
      get { return _SectionTypeName; }
      set { _SectionTypeName = value; }
    }
    private string _PassIntro = "";
    [global::ProtoBuf.ProtoMember(36, IsRequired = false, Name=@"PassIntro", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string PassIntro
    {
      get { return _PassIntro; }
      set { _PassIntro = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}