//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: StageEventHandlerData.proto
namespace StageEventHandlerData
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StageEventHandlerDatatable")]
  public partial class StageEventHandlerDatatable : global::ProtoBuf.IExtensible
  {
    public StageEventHandlerDatatable() {}
    
    private string _tname = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string tname
    {
      get { return _tname; }
      set { _tname = value; }
    }
    private readonly global::System.Collections.Generic.List<StageEventHandlerData> _tlist = new global::System.Collections.Generic.List<StageEventHandlerData>();
    [global::ProtoBuf.ProtoMember(2, Name=@"tlist", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<StageEventHandlerData> tlist
    {
      get { return _tlist; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StageEventHandlerData")]
  public partial class StageEventHandlerData : global::ProtoBuf.IExtensible
  {
    public StageEventHandlerData() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private bool _IsNeedLoadRes = default(bool);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"IsNeedLoadRes", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool IsNeedLoadRes
    {
      get { return _IsNeedLoadRes; }
      set { _IsNeedLoadRes = value; }
    }
    private bool _ForbidCalledAtInit = default(bool);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"ForbidCalledAtInit", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool ForbidCalledAtInit
    {
      get { return _ForbidCalledAtInit; }
      set { _ForbidCalledAtInit = value; }
    }
    private string _Group = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"Group", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Group
    {
      get { return _Group; }
      set { _Group = value; }
    }
    private int _Index = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"Index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Index
    {
      get { return _Index; }
      set { _Index = value; }
    }
    private string _Name = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"Name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Name
    {
      get { return _Name; }
      set { _Name = value; }
    }
    private string _Des = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"Des", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Des
    {
      get { return _Des; }
      set { _Des = value; }
    }
    private string _Param1Name = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"Param1Name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Param1Name
    {
      get { return _Param1Name; }
      set { _Param1Name = value; }
    }
    private int _Param1SourceType = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"Param1SourceType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Param1SourceType
    {
      get { return _Param1SourceType; }
      set { _Param1SourceType = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _Param1SelectObjectType = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(10, Name=@"Param1SelectObjectType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> Param1SelectObjectType
    {
      get { return _Param1SelectObjectType; }
    }
  
    private string _Param1EnumTag = "";
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"Param1EnumTag", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Param1EnumTag
    {
      get { return _Param1EnumTag; }
      set { _Param1EnumTag = value; }
    }
    private string _Param2Name = "";
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"Param2Name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Param2Name
    {
      get { return _Param2Name; }
      set { _Param2Name = value; }
    }
    private int _Param2SourceType = default(int);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"Param2SourceType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Param2SourceType
    {
      get { return _Param2SourceType; }
      set { _Param2SourceType = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _Param2SelectObjectType = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(14, Name=@"Param2SelectObjectType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> Param2SelectObjectType
    {
      get { return _Param2SelectObjectType; }
    }
  
    private string _Param2EnumTag = "";
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"Param2EnumTag", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Param2EnumTag
    {
      get { return _Param2EnumTag; }
      set { _Param2EnumTag = value; }
    }
    private string _Param3Name = "";
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"Param3Name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Param3Name
    {
      get { return _Param3Name; }
      set { _Param3Name = value; }
    }
    private int _Param3SourceType = default(int);
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"Param3SourceType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Param3SourceType
    {
      get { return _Param3SourceType; }
      set { _Param3SourceType = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _Param3SelectObjectType = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(18, Name=@"Param3SelectObjectType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> Param3SelectObjectType
    {
      get { return _Param3SelectObjectType; }
    }
  
    private string _Param3EnumTag = "";
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"Param3EnumTag", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Param3EnumTag
    {
      get { return _Param3EnumTag; }
      set { _Param3EnumTag = value; }
    }
    private string _Param4Name = "";
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"Param4Name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Param4Name
    {
      get { return _Param4Name; }
      set { _Param4Name = value; }
    }
    private int _Param4SourceType = default(int);
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"Param4SourceType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Param4SourceType
    {
      get { return _Param4SourceType; }
      set { _Param4SourceType = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _Param4SelectObjectType = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(22, Name=@"Param4SelectObjectType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> Param4SelectObjectType
    {
      get { return _Param4SelectObjectType; }
    }
  
    private string _Param4EnumTag = "";
    [global::ProtoBuf.ProtoMember(23, IsRequired = false, Name=@"Param4EnumTag", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Param4EnumTag
    {
      get { return _Param4EnumTag; }
      set { _Param4EnumTag = value; }
    }
    private string _Param5Name = "";
    [global::ProtoBuf.ProtoMember(24, IsRequired = false, Name=@"Param5Name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Param5Name
    {
      get { return _Param5Name; }
      set { _Param5Name = value; }
    }
    private int _Param5SourceType = default(int);
    [global::ProtoBuf.ProtoMember(25, IsRequired = false, Name=@"Param5SourceType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Param5SourceType
    {
      get { return _Param5SourceType; }
      set { _Param5SourceType = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _Param5SelectObjectType = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(26, Name=@"Param5SelectObjectType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> Param5SelectObjectType
    {
      get { return _Param5SelectObjectType; }
    }
  
    private string _Param5EnumTag = "";
    [global::ProtoBuf.ProtoMember(27, IsRequired = false, Name=@"Param5EnumTag", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Param5EnumTag
    {
      get { return _Param5EnumTag; }
      set { _Param5EnumTag = value; }
    }
    private string _Param6Name = "";
    [global::ProtoBuf.ProtoMember(28, IsRequired = false, Name=@"Param6Name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Param6Name
    {
      get { return _Param6Name; }
      set { _Param6Name = value; }
    }
    private int _Param6SourceType = default(int);
    [global::ProtoBuf.ProtoMember(29, IsRequired = false, Name=@"Param6SourceType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Param6SourceType
    {
      get { return _Param6SourceType; }
      set { _Param6SourceType = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _Param6SelectObjectType = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(30, Name=@"Param6SelectObjectType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> Param6SelectObjectType
    {
      get { return _Param6SelectObjectType; }
    }
  
    private string _Param6EnumTag = "";
    [global::ProtoBuf.ProtoMember(31, IsRequired = false, Name=@"Param6EnumTag", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Param6EnumTag
    {
      get { return _Param6EnumTag; }
      set { _Param6EnumTag = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}