//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: StageData.proto
namespace StageData
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StageDatatable")]
  public partial class StageDatatable : global::ProtoBuf.IExtensible
  {
    public StageDatatable() {}
    
    private string _tname = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string tname
    {
      get { return _tname; }
      set { _tname = value; }
    }
    private readonly global::System.Collections.Generic.List<StageData> _tlist = new global::System.Collections.Generic.List<StageData>();
    [global::ProtoBuf.ProtoMember(2, Name=@"tlist", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<StageData> tlist
    {
      get { return _tlist; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StageData")]
  public partial class StageData : global::ProtoBuf.IExtensible
  {
    public StageData() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private int _TimeLimit = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"TimeLimit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int TimeLimit
    {
      get { return _TimeLimit; }
      set { _TimeLimit = value; }
    }
    private string _SceneName = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"SceneName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string SceneName
    {
      get { return _SceneName; }
      set { _SceneName = value; }
    }
    private string _MapConfigDataPath = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"MapConfigDataPath", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string MapConfigDataPath
    {
      get { return _MapConfigDataPath; }
      set { _MapConfigDataPath = value; }
    }
    private int _Terrain = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"Terrain", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Terrain
    {
      get { return _Terrain; }
      set { _Terrain = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _TerrainModifyAttr = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(6, Name=@"TerrainModifyAttr", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> TerrainModifyAttr
    {
      get { return _TerrainModifyAttr; }
    }
  
    private string _TerrainAttrShow = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"TerrainAttrShow", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string TerrainAttrShow
    {
      get { return _TerrainAttrShow; }
      set { _TerrainAttrShow = value; }
    }
    private string _play = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"play", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string play
    {
      get { return _play; }
      set { _play = value; }
    }
    private int _StageType = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"StageType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int StageType
    {
      get { return _StageType; }
      set { _StageType = value; }
    }
    private int _BgSoundId = default(int);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"BgSoundId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int BgSoundId
    {
      get { return _BgSoundId; }
      set { _BgSoundId = value; }
    }
    private float _time = default(float);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float time
    {
      get { return _time; }
      set { _time = value; }
    }
    private float _pvpCameraDelay = default(float);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"pvpCameraDelay", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float pvpCameraDelay
    {
      get { return _pvpCameraDelay; }
      set { _pvpCameraDelay = value; }
    }
    private string _skyBoxName = "";
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"skyBoxName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string skyBoxName
    {
      get { return _skyBoxName; }
      set { _skyBoxName = value; }
    }
    private readonly global::System.Collections.Generic.List<float> _attackFormationParam = new global::System.Collections.Generic.List<float>();
    [global::ProtoBuf.ProtoMember(14, Name=@"attackFormationParam", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public global::System.Collections.Generic.List<float> attackFormationParam
    {
      get { return _attackFormationParam; }
    }
  
    private readonly global::System.Collections.Generic.List<float> _defendFormationParam = new global::System.Collections.Generic.List<float>();
    [global::ProtoBuf.ProtoMember(15, Name=@"defendFormationParam", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public global::System.Collections.Generic.List<float> defendFormationParam
    {
      get { return _defendFormationParam; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}