//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class GameCore_UpdateManagerWrap
{
	public static void Register(LuaState L)
	{
		L.BeginStaticLibs("UpdateManager");
		L.RegFunction("Update", Update);
		L.EndStaticLibs();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Update(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			GameCore.UpdateManager.Update();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

